host: 0.0.0.0
# Configuración del sitio
url: "https://kibzai.github.io"
baseurl: "/Programas"
username: Kibzai
title: Kib Programas
description: Programas, Configuraciones, Protocolos & Aplicaciones para desarrollo y programación

# Configuración de compilación
sass:
  style: compressed

# Plugins de Jekyll
plugins:
  - jekyll-sass-converter
  - jekyll-feed

# Build settings
lsi: false             # Latent Semantic Indexing for related posts, set to false for faster builds
safe: true             # Safe mode, restricts custom plugins for GitHub Pages compatibility
source: .              # Source directory is the root
incremental: false     # Incremental build, set to false for full rebuilds
highlighter: rouge     # Syntax highlighter

# Gist settings
gist:
  noscript: false      # Allows Gists to work without JavaScript

# Configuración de Markdown
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

collections:
  tools:
    output: true